name: Pull Request Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check API Contracts
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get changed OpenAPI files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            specs/**/*.yaml
            specs/**/*.yml
            specs/**/*.json

      - name: Run Spectral linter on changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "Running Spectral linter on: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          FILES=$(find specs -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \))
          docker run --rm -v "$(pwd):/repo:rw" -w /repo stoplight/spectral:6.15.1 lint $FILES

      - name: Run OpenAPI backward compatibility check
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker run -v "$(pwd):/repo:rw" -w /repo \
            --user $(id -u):$(id -g) \
            specmatic/specmatic backward-compatibility-check --repo-dir=/repo --base-branch=origin/main
